# Generated by Django 2.2.3 on 2019-12-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20191209_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='overs',
            field=models.IntegerField(),
        ),
    ]
