# Generated by Django 2.2.3 on 2019-12-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20191209_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ScoreCard',
        ),
    ]
